### PR TITLE
Fix Patch Inventory

### PR DESCRIPTION
**Pull request by kedodrill**
* Return the response object instead of the message.

### CODE REVIEW

**Comment by kedodrill** [comment]
~Travis is complaining bc env settings or smth~

EDIT: I'm dumb, and should've checked the actual error message. The test failed because it is expecting the message and not the response object.

**Comment by kedodrill** [comment]
~@brandon14 How did the PatchInventory test ever pass? It expects a `Response` object, yet we are returning just that string in the code. What's up with that?~

~Basically, how did this ever work?~
```
$mockClient->shouldReceive('request')->andReturns(
            new Response(
                200,
                [ 'Content-Type' => 'application/json' ],
                '{
                    "body": "Request received"
                }'
            )
        );
```

**Disregard this**, I was looking in the wrong place.

**Comment by kedodrill** [comment]
@brandon14 Okay, I think we are good. Unless you think that assertion I changed could benefit in another way or it should be changed to something else.

**Comment by brandon14** [comment]
@kedodrill I think this should be fine.

**Pull request merged**
